- _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${checkpoints_dir}
  monitor: val/total
  mode: min

- _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val/total
  mode: min

- _target_: callbacks.visualize.VisualizeLatents
  # every_n_epoch: 1
  n_components: 2
  transform:
      _target_: sklearn.manifold.TSNE
      n_components: ${n_components}
      random_state: ${seed}
  show: False
  save_path: ${outputs_dir}
  fig_kw: {}
  ax_kw: {}


- _target_: callbacks.eval.TimbreMetrics
  # every_n_epoch: 1
  sample_rate: ${audio.target_sr}
  fixed_duration: ${div:${audio.dur_samples}, ${audio.target_sr}}
  device: cuda
  heatmap_kw:
    imshow_kw: {}
    text_kw: {}