seed: 13

audio:
  target_sr: 44100
  dur_samples: ${pow:2,15}

# --- TODO: move to config/logs ---

debug: True  # log_dir = 'logs/debug' if True
project_dir: /Users/farida/fy105/cosi
log_dir_name:
  "${hydra:job.name}/\
   ${hydra:runtime.choices.features}_\
   ${hydra:runtime.choices.model}/\
   ${hydra:runtime.choices.datamodule}/\
   ${now:%Y-%m-%d_%H-%M-%S}"
log_dir:
  "${project_dir}/logs/\
  ${log_dir:${log_dir_name}, ${debug}}"
checkpoints_dir: ${log_dir}/checkpoints
outputs_dir: ${log_dir}/outputs

hydra:
  # searchpath:  # for train_kubeflow.ipynb
  # - file:///workspace/files/cosi
  run:
    dir: ${log_dir}
  output_subdir: hydra
  sweep:
    dir: ${log_dir}/sweeps
    
wandb:
  save_dir: ${log_dir}
  project: cosi
  run: relaunch

# ------

trainer:
  _target_: lightning.pytorch.Trainer
  fast_dev_run: True
  deterministic: warn
  accelerator: gpu
  devices: 1
  min_epochs: 10
  max_epochs: 50
  check_val_every_n_epoch: 1
  precision: 16-mixed
  strategy: ddp
  default_root_dir: ${checkpoints_dir}  # TODO: change
  profiler: simple

defaults:
  - features: jtfs
  - datamodule: sol_pmt
  - transform: default
  - model: supervised_sle_classifier
  - optim: default
  - callbacks: default
  - _self_

features:
  sr: ${audio.target_sr}
  device: cuda

datamodule:
  batch_size: 32
  num_workers: 6
  transform: ${transform}
  # sampler:
  # collate_fn:
