seed: 13

audio:
  target_sr: 44100
  dur_samples: ${pow:2,15}

# --- TODO: move to config/logs ---

debug: True  # log_dir = 'logs/debug' if True
project_dir: /files/cosi  # ${oc.env:HOME}/cosi
log_dir_name:
  "${hydra:job.name}/\
   ${hydra:runtime.choices.features}_\
   ${hydra:runtime.choices.model}/\
   ${get_basename:${hydra:runtime.choices.net}}/\
   ${hydra:runtime.choices.datamodule}/\
   ${now:%Y-%m-%d_%H-%M-%S}"
log_dir:
  "${project_dir}/logs/\
  ${log_dir:${log_dir_name}, ${debug}}"
checkpoints_dir: ${log_dir}/checkpoints
outputs_dir: ${log_dir}/outputs

hydra:
  searchpath:
  - file:///workspace/files/cosi
  run:
    dir: ${log_dir}
  output_subdir: hydra
  sweep:
    dir: ${log_dir}/sweeps
    
wandb:
  save_dir: ${log_dir}
  project: cosi
  run: pilot-timbre

# ------

trainer:
  _target_: lightning.pytorch.Trainer
  fast_dev_run: 4
  deterministic: warn
  accelerator: gpu
  devices: 1
  min_epochs: 10
  max_epochs: 50
  check_val_every_n_epoch: 1
  precision: 16-mixed
  strategy: ddp
  default_root_dir: ${checkpoints_dir}  # TODO: change
  profiler: simple

defaults:
  - features: jtfs
  - datamodule: local/sol
  - transform: default
  - net: autoencoder/conv
  - model: autoencoder
  - optim: default
  - callbacks: debug # default
  # - logs: local/default
  - _self_

features:
  sr: ${audio.target_sr}
  device: cuda

datamodule:
  batch_size: 32
  num_workers: 6
  transform: ${transform}
  # sampler:
  # collate_fn:

net:
  sr: ${audio.target_sr}

model:
  loss_fn:
    _target_: torch.nn.MSELoss
  loss_weights:
    recon: 1.0
