- _target_: data.transforms.Normalize
# TODO: add https://iver56.github.io/audiomentations/waveform_transforms/trim/
- _target_: data.transforms.EqualizeDuration
  sr: ${audio.target_sr}
  dur_samples: ${audio.dur_samples}
