- _target_: utils.audio.Normalize
# TODO: add https://iver56.github.io/audiomentations/waveform_transforms/trim/
- _target_: utils.audio.EqualizeDuration
  sr: ${audio.target_sr}
  dur_samples: ${audio.dur_samples}
